//
// Created by petr on 12/19/19.
//

#ifndef GMU_FLUID_SIMULATION_CELLULAR_AUTOMATA_UI_H
#define GMU_FLUID_SIMULATION_CELLULAR_AUTOMATA_UI_H

class UI {};

#endif // GMU_FLUID_SIMULATION_CELLULAR_AUTOMATA_UI_H
